export const reportColors = {
  navy: [15, 23, 42],
  blue: [37, 99, 235],
  green: [22, 163, 74],
  orange: [249, 115, 22],
  red: [220, 38, 38],
  purple: [124, 58, 237],
  gray: [100, 116, 139],
  lightBlue: [239, 246, 255],
  lightGray: [248, 250, 252],
};

export function drawHeader(pdf, title, pageNo) {
  const pageWidth = pdf.internal.pageSize.getWidth();

  pdf.setFillColor(...reportColors.navy);
  pdf.rect(0, 0, pageWidth, 28, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.text("SmartStock AI", 14, 12);

  pdf.setFontSize(9);
  pdf.text(title, 14, 20);

  pdf.text(`Page ${pageNo}`, pageWidth - 28, 18);

  pdf.setTextColor(...reportColors.navy);
}

export function drawFooter(pdf) {
  const pageHeight = pdf.internal.pageSize.getHeight();

  pdf.setFontSize(8);
  pdf.setTextColor(...reportColors.gray);
  pdf.text(
    "Generated by SmartStock AI · Version 4 Enterprise",
    14,
    pageHeight - 10
  );
}

export function sectionTitle(pdf, title, y) {
  pdf.setFontSize(15);
  pdf.setTextColor(...reportColors.blue);
  pdf.text(title, 14, y);

  pdf.setDrawColor(219, 234, 254);
  pdf.line(14, y + 3, 196, y + 3);

  pdf.setTextColor(...reportColors.navy);
}

export function kpiCard(pdf, label, value, x, y, color = reportColors.blue) {
  pdf.setFillColor(...reportColors.lightGray);
  pdf.setDrawColor(226, 232, 240);
  pdf.roundedRect(x, y, 55, 26, 4, 4, "FD");

  pdf.setFontSize(8);
  pdf.setTextColor(...reportColors.gray);
  pdf.text(label, x + 4, y + 8);

  pdf.setFontSize(14);
  pdf.setTextColor(...color);
  pdf.text(String(value), x + 4, y + 20);

  pdf.setTextColor(...reportColors.navy);
}

export function progressBar(pdf, label, value, x, y, color = reportColors.green) {
  pdf.setFontSize(9);
  pdf.setTextColor(...reportColors.gray);
  pdf.text(label, x, y);

  pdf.setFillColor(226, 232, 240);
  pdf.roundedRect(x, y + 4, 80, 6, 3, 3, "F");

  pdf.setFillColor(...color);
  pdf.roundedRect(x, y + 4, Math.min(value, 100) * 0.8, 6, 3, 3, "F");

  pdf.setTextColor(...reportColors.navy);
  pdf.text(`${value}%`, x + 86, y + 9);
}